# Generated by Django 4.2 on 2023-04-18 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField(null=True)),
                ('doctor_id', models.PositiveIntegerField(null=True)),
                ('patient_name', models.CharField(max_length=40, null=True)),
                ('doctor_name', models.CharField(max_length=40, null=True)),
                ('appointment_date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_DischargeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField(null=True)),
                ('patient_name', models.CharField(max_length=40)),
                ('assigned_doctor_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('admit_date', models.DateField()),
                ('release_date', models.DateField()),
                ('day_spent', models.PositiveIntegerField()),
                ('room_charge', models.PositiveIntegerField()),
                ('medicine_cost', models.PositiveIntegerField()),
                ('doctor_fees', models.PositiveIntegerField()),
                ('Other_charges', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pics', models.ImageField(blank=True, null=True, upload_to='profilePics/Patients_pics')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100)),
                ('Doctor_assigned_ID', models.PositiveIntegerField(null=True)),
                ('Date_Admitted', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pics', models.ImageField(blank=True, null=True, upload_to='profilePics/Doctor_pics')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('units', models.CharField(choices=[('Family Depart', 'Family Physicians'), ('allergy Depart', 'Allergists/Immunologists'), ('Anesthesiology Depart', 'Anesthesiologists'), ('Heart Treatment Depart', 'Cardiologists'), ('Lower Abnonimal Depart', 'Colon and Rectal Surgeons'), ('Critical Care Depart', 'Critical Care Medicine Specialists'), ('Skincare Depart', 'Dermatologists'), ('Endocrinology Depart', 'Endocrinologists'), ('Gastroenterology Depart', 'Gastroenterologists'), ('geriatric Depart', 'Geriatric Medicine Specialists'), ('Emergency Medicine depart', 'Emergency Medicine Specialists')], default='Family Depart', max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
